version: '3.3'

volumes:
  static:
  media:
  pg_data:
  
services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    env_file: ./.env
    build: backend
    volumes:
      - static:/app/backend_static
      - media:/app/media
  frontend:
    depends_on:
      - backend
    build: ./frontend
  nginx:
    build: ./nginx
    ports:
      - "9000:80"
    volumes:
      - static:/static/
      - media:/media/

