import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "./components/footer";
import NavBar from "./components/nav-bar";
import StoreProvider from "./StoreProvider"


const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="rus">
      <body className={inter.className}>
        <StoreProvider>
            <NavBar />{children}<Footer />
        </StoreProvider>
      </body>
    </html >
  );
}
