# Generated by Django 4.2 on 2024-04-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productadvantage',
            options={'ordering': ('product',), 'verbose_name': 'Преимущество товара', 'verbose_name_plural': 'Преимущества товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='productadvantage',
            name='advantage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.advantage', verbose_name='Преимущество'),
        ),
        migrations.AlterField(
            model_name='productadvantage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product', verbose_name='Товар'),
        ),
    ]
