# Generated by Django 4.2 on 2024-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'default_related_name': 'inOrder', 'ordering': ('product',), 'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
    ]
