# Generated by Django 4.2 on 2024-03-30 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='description',
        ),
        migrations.AddField(
            model_name='advantage',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Преимущество'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='advantages',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.SmallIntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('products', models.ManyToManyField(to='shopapp.productsinorder', verbose_name='Товары')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='advantages',
            field=models.ManyToManyField(to='shopapp.advantage', verbose_name='Преимущества'),
        ),
    ]
