# Generated by Django 4.2 on 2024-04-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_productadvantage_options_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'ordering': ('title',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'default_related_name': 'inOrder', 'ordering': ('product',), 'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
    ]
