# Generated by Django 4.2 on 2024-04-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_productadvantage_options_alter_product_image_and_more'),
        ('shopapp', '0002_alter_productsinorder_options'),
    ]

    operations = [
    ]
