# Generated by Django 4.2 on 2024-04-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_product_options_alter_productsinorder_options'),
        ('shopapp', '0003_merge_20240409_2305'),
    ]

    operations = [
    ]
