# Generated by Django 4.2 on 2024-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_product_options_alter_productsinorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'product', 'ordering': ('title', '-title'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='sales_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
