# Generated by Django 4.2 on 2024-04-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_product_options_product_sales_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_number',
        ),
    ]
